Repository MaynardMiner/SWARM, pull requests merged in 2019-03, with the labels that each got.

#26 Allow specifying more levels for fans speed
  build/powershell/octune.ps1
Labels: enhancement, non-essential feature

#75 OC - Added details for memory voltage and fan speed setting on AMD Wi…
  config/oc/new_sample.json
Labels: update request, windows

#76 Pulling updates to master to my develop branch
  config/oc/new_sample.json
Labels: Alpha
